### PR TITLE
Subset composition

### PR DESCRIPTION
**Pull request by traiansf**
Refactorings and some properties about projections of traces on a subset of nodes, including relating no-equivocation constraints.

Only the final 3 commits are relevant (the others are part of PR #172)

To be merged after PR #172.

### CODE REVIEW

**Review by bmmoore — COMMENTED** [review]
I reviewed just the last 3 commits,
a03911f
c4f99a3
cff474a

Those looks ok, but it's not all the history. Let's finish #172, then it will be easier to make sure I'm covering everything.

**Comment by traiansf** [comment]
@bmmoore I've incorporated your suggestion and integrated changes from master so now it's standalone. Please take another look.

**Review by bmmoore — APPROVED** [review]
I've reviewed the full changes vs. master now. Looks good.

Have you looked at the `generic_projection` branch? The projection operation there is definitely flexible enough to cover the projection part of SubProjectionTraces. Probably a useful example for you to get some idea of how useful it might be for the size of the code. I haven't gone over all the other lemmas in SubProjectionTraces to see which might also be provable more generically.

**Comment by traiansf** [comment]
> Have you looked at the `generic_projection` branch? The projection operation there is definitely flexible enough to cover the projection part of SubProjectionTraces. Probably a useful example for you to get some idea of how useful it might be for the size of the code. I haven't gone over all the other lemmas in SubProjectionTraces to see which might also be provable more generically.

I've taken a look now, thanks for the reminder.  I think it looks great and it would be nice to integrate it into master and redo the existing projections using it.

**Pull request merged**
